# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e7113c9fcc454ec8114966c1b6a3617aa3874ccb904a30c10985a0d79eaf0fc399b819acb82ecefa88fe67f42bde967ce278de0b5c2b5ee9dee8e10455e972e

test:
  secret_key_base: a33b891ce9e72c1f6332001731e451719e90e55a309f53f5377924a3293452d0949a085ac7b5754eb62df0b8e722df93550bd2f7a3e1f47b877c9e27e2ab4b70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
